"""phone number type as column val

Revision ID: 69e164dd28cc
Revises: 28105e145a8b
Create Date: 2021-12-29 00:30:30.803796

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '69e164dd28cc'
down_revision = '28105e145a8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_number', sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20), nullable=True))
    op.drop_index('_phone_number', table_name='user')
    op.create_unique_constraint(None, 'user', ['phone_number'])
    op.drop_column('user', 'phone_country_code')
    op.drop_column('user', '_phone_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_phone_number', mysql.VARCHAR(length=20), nullable=False))
    op.add_column('user', sa.Column('phone_country_code', mysql.VARCHAR(length=8), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('_phone_number', 'user', ['_phone_number', 'phone_country_code'], unique=False)
    op.drop_column('user', 'phone_number')
    # ### end Alembic commands ###
